# Generated by Django 5.2.1 on 2025-07-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="room",
            field=models.CharField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name="message",
            name="user",
            field=models.CharField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name="room",
            name="name",
            field=models.CharField(max_length=1000),
        ),
    ]
